runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.1"

handlers:
- url: /static/css/style.min.css
  static_files: static/css/style.min.css
  upload: static/css/style.min.css

- url: /static/js/script.min.js
  static_files: static/js/script.min.js
  upload: static/js/script.min.js

- url: /static/assets
  static_dir: static/assets/

- url: /_ah/admin(/.*)?
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: /admin
  script: main.app
  login: admin
  secure: always

- url: /.*
  script: main.app
  secure: always
