runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.1"

handlers:
- url: /_ah/admin(/.*)?
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: /.*
  script: main.app
